# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# Firebase
pod 'Firebase/Core'
pod 'Firebase/Messaging'

# Post installation for iOS 12
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end